# Generated by Django 4.0.1 on 2022-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='rate',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
