# Generated by Django 4.0.1 on 2022-01-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0002_currencymodel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='fromcurrency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='tocurrency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
