# Generated by Django 4.0.1 on 2022-01-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0003_alter_currencymodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='Data_currency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
